### ISSUE TITLE
sqlite3.IntegrityError: UNIQUE constraint failed: interval.id

### ISSUE THREAD

**Issue by lbeltrame** [robinandeer/chanjo#125]
This occurs with a BED file from a commercial kit (http://www.qiagen.com/~/media/genetable/ng/hs/50/nghs-501x-covered; might require registration). 

```
chanjo build ../NGHS-501X-Covered.bed 
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 928, in _execute_context
    context)
  File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/default.py", line 433, in do_executemany
    cursor.executemany(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: interval.id
```

**Comment by robinandeer** [comment]
The error occurs because Chanjo (using the BED standard) expects the fourth column to serve as a (unique) ID for each interval.

I haven't written the build command to support all normal BED-files actually. Instead this is what ``chanjo convert`` is for; as an intermediate step that outputs a unified format that ``chanjo build`` can use. ``chanjo convert`` supports plugins (default: ccds) that can handle different inputs like this one from Qiagen.

If I have time I might find it interesting enough to write a new ``convert`` plugin that accepts a Qiagen BED file :wink:

**Comment by robinandeer** [comment]
We will focus more on supporting any general BED format but we will still require a 4th column to be a unique ID
