### ISSUE TITLE
chanjo export not working

### ISSUE THREAD

**Issue by roryk** [robinandeer/chanjo#134]
It looks like export is missing a positional argument parser:

```
vagrant@vagrant-ubuntu-trusty-64:/v-data/bcbio-nextgen/tests/test_automated_output/coverage$ /usr/local/share/bcbio/anaconda/bin/chanjo export PairedBatch2-coverage.db
Usage: chanjo export [OPTIONS]

Error: Got unexpected extra argument (PairedBatch2-coverage.db)
```

**Comment by robinandeer** [comment]
Ahh, I see; this is due to how [Click](http://click.pocoo.org/4/) is setup to handle nested commands. It can get a little tricky I agree but essentially I try to keep the interface DRY so if an option is relevant for multiple subcommands you need to supply it after ``chanjo`` but before ``export``. This has changed since Chanjo 1.x so now you would do:

```bash
$ chanjo --db PairedBatch2-coverage.db export
```

And for another command that also needs to know about a database:

```bash
$ chanjo --db PairedBatch2-coverage.db import coverage-annotations.bed
```

But I just realized this is not consistently reflected in the online documentation so I will fix that - thank you for the bug report!
